version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-server-template
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "4000:4000"
      - "8080:8080"
      
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
